# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-12 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('c_date', models.CharField(max_length=100)),
                ('in_out', models.IntegerField()),
                ('money', models.FloatField()),
                ('remark', models.CharField(max_length=255, null=True)),
                ('sync_type', models.IntegerField()),
                ('type_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=255)),
                ('modify_time', models.IntegerField(help_text='\u6570\u5b57\u65f6\u95f4\u6233')),
            ],
        ),
        migrations.CreateModel(
            name='MonthCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('in_out', models.IntegerField()),
                ('money', models.FloatField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('sync_type', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('modify_time', models.IntegerField()),
            ],
        ),
    ]
